name: hello world

on:
  push:
    branches: [main]
  # workflow_dispatch: 

  # repository_dispatch:
  #    types:
  #      - run_tests


jobs:
  greet:
   if: ${{ github.repository == 'hanokchinni004-ui/Actions' }}
   runs-on: ubuntu-latest
   steps:
      - name: Say Hello
        run:  echo "Hello World"
  hello_mf:
    runs-on: ubuntu-latest
    steps:
      - name: mf_
        run: echo  "hello mf"
