name: hello world

on:
  push:
    branches: [main]
  # workflow_dispatch: 

  # repository_dispatch:
  #    types:
  #      - run_tests


jobs:
  greet:
   if: ${{ github.repository == 'hanokchinni004-ui/Actions' }}
   runs-on: ubuntu-latest
   steps:
      - name: Say Hello
        run:  echo "Hello World"
  hello_mf:
    runs-on: ubuntu-latest
    steps:
      - name: group_mf
        run: |
          echo '::group::New Group'
          echo 'group 1'
          echo 'group 2'
          echo 'group 3'
          echo '::endgroup::'
