name: Run Tests

on:
   push:
   workflow_dispatch:


jobs:
   test_job:
      runs-on: ubuntu-latest
      steps:
         -name: checkout code
          uses: actions/checkout@v4

         -name: run test script
          run:  bash scripts/run-tests.sh